---
name: DateTime-Format-Natural-EN
version: 0.05
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Create machine readable date/time with natural parsing logic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  DateTime::Format::Natural::EN:
    file: lib/DateTime/Format/Natural/EN.pm
    version: 0.05
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
